name: "Labeler"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  triage:
    name: "Triage"
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Bot: Labeler Triage"
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
