name: "Build"

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      os:
        required: true
        type: string
      label:
        required: true
        type: string
      flags:
        required: false
        type: string
        default: "--no-configuration-cache"
      java:
        required: false
        type: string
        default: 20
      coverage:
        required: false
        type: boolean
        default: true
      provenance:
        required: false
        type: boolean
        default: true
      experimental:
        required: false
        type: boolean
        default: false
    secrets:
      SONAR_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true
      BUILDLESS_APIKEY:
        required: true

env:
  CI: "true"
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:+UseParallelGC -Xmx3g -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M"
  GRADLE_CACHE_LOCAL: true
  GRADLE_CACHE_REMOTE: true
  GRADLE_CACHE_PUSH: true
  GRADLE_CACHE_USERNAME: apikey
  GRADLE_CACHE_PASSWORD: ${{ secrets.BUILDLESS_APIKEY }}
  CACHE_ENDPOINT: https://gradle.less.build/cache/generic/
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  TEST_EXCEPTIONS: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    name: "Compile and Test"

    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "write"

    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v3
      - name: "Setup: Cache"
        uses: buildjet/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          path: |
            ~/.sonar/cache
            ~/.konan
            ~/.gradle/caches
      - name: "Setup: Zulu 20"
        uses: buildjet/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'
      - name: "Build and Test"
        uses: gradle/gradle-build-action@v2
        id: gradlebuild
        continue-on-error: ${{ inputs.experimental }}
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/beta' }}
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
          gradle-home-cache-excludes: |
            caches/build-cache-1
            caches/keyrings
          arguments: |
            preMerge
            -PVERSION=1.0-SNAPSHOT
            -PsonarScan=true
            --scan
            --no-daemon
            --warning-mode=none
            --dependency-verification=lenient
            -Pci=true
            ${{ inputs.flags }}
      - name: "Build: Provenance Subject"
        id: hash
        if: inputs.provenance
        run: |
          echo "hashes=$(sha256sum ./build/libs/* | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: "Analysis: Build Reports"
        uses: actions/upload-artifact@v3
        if: failure() || success()
        with:
          name: reports
          path: |
            build/api/
            build/reports/
            build/spdx/
            build/test-results/
      - name: "Report: Codecov (Server)"
        if: inputs.coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/kover/report.xml

  ## Report: Provenance
  provenance:
    name: Provenance
    needs: [build]
    if: inputs.provenance
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.7.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: false
